import type { AutographExchangeCopy } from "./types";
import { REQUEST_PROMPTS, SIGNATURE_IDEAS } from "./screen-utils";

export const DEFAULT_AUTOGRAPH_COPY: AutographExchangeCopy = {
  signedOutKicker: "Autograph Exchange",
  signedOutTitle: "A warm, simple place to ask and give autographs",
  signedOutBenefitOneTitle: "Ask with context",
  signedOutBenefitOneCopy: "Choose one person and explain why their autograph matters to you.",
  signedOutBenefitTwoTitle: "Reply without confusion",
  signedOutBenefitTwoCopy: "Incoming requests stay in one clear inbox until you respond.",
  signedOutBenefitThreeTitle: "Keep every memory",
  signedOutBenefitThreeCopy: "Signed autographs are saved in one archive you can revisit anytime.",
  signedOutBenefitsLabel: "Why autograph exchange feels easy",
  heroKicker: "Autograph Exchange",
  heroTitle: "Collect thoughtful autographs without guesswork or clutter",
  heroGuidanceLabel: "What to do next",
  bookPreviewLabel: "Autograph book preview",
  bookCoverLabel: "Open autograph book",
  bookLeftPageLabel: "Request page",
  bookLeftPageTitle: "Ask one person at a time",
  bookLeftPageDetail: "A short, specific note gives every signer a real reason to write back.",
  bookRightPageLabel: "Signed page",
  bookRightPageTitle: "Save the reply as a keepsake",
  bookRightPageDetail: "Signed notes land in a searchable collection you can export and revisit.",
  bookSentLabel: "sent",
  bookWaitingLabel: "waiting",
  bookSignedLabel: "saved",
  bookTrustLine: "Each page keeps who asked, who signed, and when it became part of the collection.",
  bookExportLine: "Export-ready pages make the digital autograph feel lasting.",
  nextActionProfile: "Start by saving your profile so people know who you are.",
  nextActionInbox: "You have autograph requests waiting. Open one and reply with your autograph.",
  nextActionComposer: "Pick one person and ask for an autograph with a short personal note.",
  nextActionWaitingForProfiles: "You are ready. Once others create profiles, you can start exchanging autographs.",
  quickStepsAriaLabel: "How autograph exchange works",
  journeyTitle: "Build a collection worth coming back to",
  journeySubtitle: "Each autograph becomes a keepsake. Save your profile, ask thoughtfully, and grow an archive you will actually want to revisit.",
  journeyProfileLabel: "Profile ready",
  journeyRequestLabel: "Requests sent",
  journeyCollectLabel: "Autographs collected",
  nextMilestoneLabel: "Next milestone",
  completeLabel: "complete",
  doneLabel: "Done",
  nextLabel: "Next",
  celebrationTitle: "New autograph added",
  celebrationDetail: "Your archive just grew. Open Signed Autographs to revisit it any time.",
  stepOne: "Step 1",
  stepTwo: "Step 2",
  stepThree: "Step 3",
  stepOneTitle: "Set up once",
  stepOneDetail: "Save your name and role so others can find you.",
  stepTwoTitle: "Ask with context",
  stepTwoDetail: "Choose one person and say why you want their autograph.",
  stepThreeTitle: "Reply from inbox",
  stepThreeDetail: "Open requests, write your autograph, and it moves to the archive.",
  requestsSent: "Requests you sent",
  requestsForYou: "Requests for you",
  signedAutographs: "Signed autographs",
  pendingStatusLabel: "Pending",
  signedStatusLabel: "Signed",
  collectionEmptySummary: "Your first signed autograph will start a collection you can keep coming back to.",
  collectionFirstSummary: "Your first keepsake is in. This is where your most meaningful signed notes begin to live.",
  collectionStarterSummary: "You have {count} signed keepsakes. Your collection is starting to feel personal and memorable.",
  collectionGrowingSummary: "You have {count} signed keepsakes. This is becoming a real archive of meaningful messages.",
  collectionArchiveSummary: "You have {count} signed keepsakes. Your archive now feels like a living collection worth revisiting again and again.",
  collectionTitle: "Your keepsake collection",
  collectionSubtitle: "Every signed autograph becomes part of a collection you can revisit, search, and treasure over time.",
  collectionPieceLabel: "Collection piece",
  revealTitle: "A new autograph has arrived",
  revealSubtitle: "Pause for a moment. This one is now part of your collection.",
  revealLabel: "Just received",
  revealFromLabel: "From",
  keepsakeMessageLabel: "Why it was requested",
  keepsakeAutographLabel: "The autograph",
  keepsakeMemoryLabel: "Saved memory",
  socialKeepsakeLabel: "Share-ready keepsake",
  shareKeepsakeLabel: "Share keepsake",
  copyKeepsakeLabel: "Copy keepsake",
  downloadKeepsakeLabel: "Download keepsake",
  downloadFormatLabel: "Download format",
  downloadSvgLabel: "SVG",
  downloadPngLabel: "PNG",
  downloadJpgLabel: "JPG",
  downloadGifLabel: "GIF",
  downloadPdfLabel: "PDF",
  keepsakeSharedStatus: "Keepsake shared.",
  keepsakeCopiedStatus: "Keepsake copied.",
  keepsakeDownloadedStatus: "Keepsake downloaded.",
  keepsakeUnavailableStatus: "Sharing is not available here yet.",
  newKeepsakeLabel: "New keepsake",
  featuredKeepsakeLabel: "Featured keepsake",
  treasuredKeepsakeLabel: "Treasured keepsake",
  savedInCollectionLabel: "Saved in your collection",
  stepNeededOnce: "Needed once",
  stepReady: "Ready to receive requests",
  stepCanAsk: "You can ask now",
  stepCompleteFirst: "Complete Step 1 first",
  profileTitle: "Your autograph profile",
  profileCompleteDescription: "Your profile is already saved, so you can skip this step unless you want to edit it.",
  profileCompleteTitle: "Profile complete",
  profileCompleteHint: "Your display name and role are already saved. You can skip Step 1 and go straight to asking or replying.",
  profileSkipHint: "Only come back here if you want to change your display name or role.",
  jumpToStepTwo: "Go to Step 2",
  profileMissingTitle: "Profile needed",
  profileMissingHint: "Save your display name and role once before sending or receiving autograph requests.",
  profileMissingDescription: "Save your display name and role once so people can ask you for an autograph.",
  savedRoleLabel: "Saved role",
  savedProfile: "Saved profile",
  savedProfileHint: "You do not need to save this every time. Edit it only if your display name or role should change.",
  signedInIdentityLabel: "Signed in as",
  signedInIdentityHint: "Your profile is saved under this identity. If you sign in with a different email later, that will be treated as a different profile.",
  editProfile: "Edit profile",
  saveChanges: "Save changes",
  saveProfile: "Save profile",
  savingProfile: "Saving profile...",
  cancel: "Cancel",
  profileAudiencePrefix: "People will see you as",
  profileAudienceConnector: "and can request an autograph from you as a",
  profileAudienceFallback: "you",
  displayNameLabel: "Display name",
  displayNameHint: "Use the name you want people to recognize right away.",
  roleLabel: "Role",
  roleHint: "Your role adds context so requests feel more personal.",
  profileFocusStartLabel: "Start here",
  profileFocusOptionalLabel: "Optional now",
  composerFocusStartLabel: "Start here",
  composerFocusLockedLabel: "Locked",
  requestComposerTitle: "Ask someone for an autograph",
  requestExplainer: "Choose one person, add a short note, and send one clear request.",
  whoShouldSign: "Who should sign for you?",
  signerSearchPlaceholder: "Search by name or role",
  signerSearchHint: "Start typing a name or role and choose one person from the suggestions.",
  signerSearchEmpty: "No matching people yet. Try another name or role.",
  signerSelectedLabel: "Selected signer",
  whyAreYouAsking: "Why are you asking?",
  requestMessagePlaceholder: "Say why you are asking and what you would love them to write.",
  requestMessageHint: "A few sincere lines are enough. Specific requests usually get warmer replies.",
  requestMetaHint: "Clear, specific requests feel more personal and are easier to answer well.",
  askForAutograph: "Send request",
  sendingRequest: "Sending request...",
  requestAlreadyPending: "Already pending",
  requestSentTitle: "Request sent",
  requestSentDetail: "Your request is now in Requests you sent. You can track it there until it is signed.",
  requestSentOutboxCta: "View sent requests",
  requestAskAnotherCta: "Ask another person",
  requestPendingForSignerHint: "You already have a pending request for this person. Open Requests you sent to track it.",
  dismissRequestFeedback: "Dismiss request message",
  nextStepCtaProfile: "Go to Step 1",
  nextStepCtaComposer: "Go to Step 2",
  nextStepCtaInbox: "Go to Step 3",
  nextStepCtaOutbox: "View sent requests",
  nextStepCtaArchive: "View signed autographs",
  saveProfileFirstHint: "Save your profile first so your request feels personal and recognizable.",
  youAreAsking: "You are asking",
  signerInboxHintPrefix: "They will see your request from",
  signerInboxHintSuffix: "and can sign it from their inbox.",
  signerInboxFallbackName: "you",
  signerListHint: "Each person appears once here. If several stored profiles look identical, we automatically show the latest one to keep this list clear.",
  requestIdeasLabel: "Request message ideas",
  requestPrompts: REQUEST_PROMPTS,
  autographIdeasLabel: "Autograph message ideas",
  signatureIdeas: SIGNATURE_IDEAS,
  inboxSubtitle: "These requests are waiting for your reply.",
  inboxFocusLabel: "Waiting on you",
  waitingCountSuffix: "waiting",
  fromPrefix: "From",
  theyAsked: "They asked",
  hideReplyBox: "Close reply box",
  writeAutograph: "Open reply box",
  openSigningFormLabel: "Open signing form for",
  signaturePlaceholder: "Write the autograph you want to give them.",
  signatureHint: "Keep it brief, warm, and personal. One thoughtful paragraph is plenty.",
  useGeneratedSignature: "Fill with signature",
  confirmSignature: "Send autograph",
  signing: "Signing...",
  outboxSubtitle: "Keep track of the requests you have already sent.",
  outboxFocusLabel: "Track here",
  pendingCountSuffix: "pending",
  archiveSubtitle: "Completed autographs are saved here in one easy-to-browse place.",
  archiveFocusLabel: "Browse here",
  totalCountSuffix: "total",
  searchPlaceholder: "Search by person or message",
  searchLabel: "Search signed autographs",
  sortLabel: "Sort signed autographs",
  newestFirst: "Newest first",
  oldestFirst: "Oldest first",
  loadMoreKeepsakes: "Load more keepsakes",
  loadingMoreKeepsakes: "Loading more...",
  requestedPrefix: "Requested",
  signedPrefix: "Signed",
  justNow: "Just now",
  recently: "Recently",
  yourAutographLabel: "Your autograph",
  noOtherProfiles: "No one else is ready yet. Once other people save a profile, they will appear here automatically.",
  noInbox: "Nothing is waiting for your autograph yet. When someone asks, it will appear here.",
  noOutbox: "You have not sent any requests yet. Start with one person and a short personal note.",
  noArchive: "No signed autographs yet. Once a request is completed, it will be saved here.",
};

export function mergeAutographCopy(copy?: Partial<AutographExchangeCopy>): AutographExchangeCopy {
  return { ...DEFAULT_AUTOGRAPH_COPY, ...copy };
}
