import type { AutographExchangeCopy } from "./types";

export const DEFAULT_AUTOGRAPH_COPY: AutographExchangeCopy = {
  heroKicker: "Autograph Exchange",
  heroTitle: "Collect thoughtful autographs without guesswork or clutter",
  journeyTitle: "Build a collection worth coming back to",
  journeySubtitle: "Each autograph becomes a keepsake. Save your profile, ask thoughtfully, and grow an archive you will actually want to revisit.",
  journeyProfileLabel: "Profile ready",
  journeyRequestLabel: "Requests sent",
  journeyCollectLabel: "Autographs collected",
  nextMilestoneLabel: "Next milestone",
  celebrationTitle: "New autograph added",
  celebrationDetail: "Your archive just grew. Open Signed Autographs to revisit it any time.",
  stepOne: "Step 1",
  stepTwo: "Step 2",
  stepThree: "Step 3",
  stepOneTitle: "Set up once",
  stepOneDetail: "Save your name and role so others can find you.",
  stepTwoTitle: "Ask with context",
  stepTwoDetail: "Choose one person and say why you want their autograph.",
  stepThreeTitle: "Reply from inbox",
  stepThreeDetail: "Open requests, write your autograph, and it moves to the archive.",
  requestsSent: "Requests you sent",
  requestsForYou: "Requests for you",
  signedAutographs: "Signed autographs",
  collectionTitle: "Your keepsake collection",
  collectionSubtitle: "Every signed autograph becomes part of a collection you can revisit, search, and treasure over time.",
  collectionPieceLabel: "Collection piece",
  revealTitle: "A new autograph has arrived",
  revealSubtitle: "Pause for a moment. This one is now part of your collection.",
  revealLabel: "Just received",
  revealFromLabel: "From",
  keepsakeMessageLabel: "Why it was requested",
  keepsakeAutographLabel: "The autograph",
  keepsakeMemoryLabel: "Saved memory",
  socialKeepsakeLabel: "Share-ready keepsake",
  shareKeepsakeLabel: "Share keepsake",
  copyKeepsakeLabel: "Copy keepsake",
  downloadKeepsakeLabel: "Download keepsake",
  keepsakeSharedStatus: "Keepsake shared.",
  keepsakeCopiedStatus: "Keepsake copied.",
  keepsakeDownloadedStatus: "Keepsake downloaded.",
  keepsakeUnavailableStatus: "Sharing is not available here yet.",
  newKeepsakeLabel: "New keepsake",
  featuredKeepsakeLabel: "Featured keepsake",
  treasuredKeepsakeLabel: "Treasured keepsake",
  savedInCollectionLabel: "Saved in your collection",
  stepNeededOnce: "Needed once",
  stepReady: "Ready to receive requests",
  stepCanAsk: "You can ask now",
  stepCompleteFirst: "Complete Step 1 first",
  profileCompleteTitle: "Profile complete",
  profileCompleteHint: "Your display name and role are already saved. You can skip Step 1 and go straight to asking or replying.",
  profileSkipHint: "Only come back here if you want to change your display name or role.",
  jumpToStepTwo: "Go to Step 2",
  profileMissingTitle: "Profile needed",
  profileMissingHint: "Save your display name and role once before sending or receiving autograph requests.",
  savedRoleLabel: "Saved role",
  savedProfile: "Saved profile",
  savedProfileHint: "You do not need to save this every time. Edit it only if your display name or role should change.",
  signedInIdentityLabel: "Signed in as",
  signedInIdentityHint: "Your profile is saved under this identity. If you sign in with a different email later, that will be treated as a different profile.",
  editProfile: "Edit profile",
  saveChanges: "Save changes",
  cancel: "Cancel",
  profileAudiencePrefix: "People will see you as",
  requestExplainer: "Choose one person, add a short note, and send one clear request.",
  whoShouldSign: "Who should sign for you?",
  signerSearchPlaceholder: "Search by name or role",
  signerSearchHint: "Start typing a name or role and choose one person from the suggestions.",
  signerSearchEmpty: "No matching people yet. Try another name or role.",
  signerSelectedLabel: "Selected signer",
  whyAreYouAsking: "Why are you asking?",
  askForAutograph: "Send request",
  saveProfileFirstHint: "Save your profile first so your request feels personal and recognizable.",
  youAreAsking: "You are asking",
  signerInboxHintPrefix: "They will see your request from",
  signerListHint: "Each person appears once here. If several stored profiles look identical, we automatically show the latest one to keep this list clear.",
  requestIdeasLabel: "Request message ideas",
  autographIdeasLabel: "Autograph message ideas",
  inboxSubtitle: "These requests are waiting for your reply.",
  waitingCountSuffix: "waiting",
  fromPrefix: "From",
  theyAsked: "They asked",
  hideReplyBox: "Close reply box",
  writeAutograph: "Open reply box",
  useGeneratedSignature: "Fill with signature",
  confirmSignature: "Send autograph",
  signing: "Signing...",
  outboxSubtitle: "Keep track of the requests you have already sent.",
  pendingCountSuffix: "pending",
  archiveSubtitle: "Completed autographs are saved here in one easy-to-browse place.",
  totalCountSuffix: "total",
  searchPlaceholder: "Search by person or message",
  searchLabel: "Search signed autographs",
  sortLabel: "Sort signed autographs",
  newestFirst: "Newest first",
  oldestFirst: "Oldest first",
  requestedPrefix: "Requested",
  signedPrefix: "Signed",
  justNow: "Just now",
  recently: "Recently",
  yourAutographLabel: "Your autograph",
  noOtherProfiles: "No one else is ready yet. Once other people save a profile, they will appear here automatically.",
  noInbox: "Nothing is waiting for your autograph yet. When someone asks, it will appear here.",
  noOutbox: "You have not sent any requests yet. Start with one person and a short personal note.",
  noArchive: "No signed autographs yet. Once a request is completed, it will be saved here.",
};

export function mergeAutographCopy(copy?: Partial<AutographExchangeCopy>): AutographExchangeCopy {
  return { ...DEFAULT_AUTOGRAPH_COPY, ...copy };
}
